server:
  port: 8082
  servlet:
    context-path:

#flyway:
#  repair: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user-service"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.flywaydb: INFO
    org.springdoc: DEBUG

springdoc:
  api-docs:
    path: /document/api-docs
  swagger-ui:
    path: /document/swagger-ui.html

jwt:
  publicKey: | 
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmqj1di5W7at8KV2C2JKO
    lNg5Pp7DB2I2As/UGwIlUjg7qTUvs43k6VBcDkwHELRISr7yVQsVSo0zugR410fR
    PW3cAiH5V1GF5QMuxzgC6DFYSvivwlaBOqitjK3BU1Ti6GVy0b5WletWq+vJNQN6
    6GXnoWln0ezYWVk+qnbrMcYmetdNrsRmbgDlCK2Dr2yfAXug2DiEU2P915Tjw8AK
    fHv2ASCxtDCQYi9dR94ZejhKVsjifidZL3sv51HxMklhz/weBYviOCmiWy9Gdh+T
    fZVzy0MRoiG3gWAekdVEgeYZW65x5LWHNrShkA3/ZzQIEv98v8GXDwAEAGhLXEIz
    2wIDAQAB
    -----END PUBLIC KEY-----

  privateKey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCaqPV2Llbtq3wp
    XYLYko6U2Dk+nsMHYjYCz9QbAiVSODupNS+zjeTpUFwOTAcQtEhKvvJVCxVKjTO6
    BHjXR9E9bdwCIflXUYXlAy7HOALoMVhK+K/CVoE6qK2MrcFTVOLoZXLRvlaV61ar
    68k1A3roZeehaWfR7NhZWT6qdusxxiZ6102uxGZuAOUIrYOvbJ8Be6DYOIRTY/3X
    lOPDwAp8e/YBILG0MJBiL11H3hl6OEpWyOJ+J1kvey/nUfEySWHP/B4Fi+I4KaJb
    L0Z2H5N9lXPLQxGiIbeBYB6R1USB5hlbrnHktYc2tKGQDf9nNAgS/3y/wZcPAAQA
    aEtcQjPbAgMBAAECggEAE1gQo4B2RPHO7MmSZQ4noTxOJKPs1s6U3NMrv1kMW/VG
    mQpa9gVIXVo8uVkPBSrXY+nwG2zwc8unbZvDlYGZDSrheq7PJfm/Wn6Eakx6KJqL
    ZY0nRpJVRYX1dwQAizCx1MljjBJXeBbgV059cxEFXW3pg8nQP3R1Nu+vo9iN4EKr
    o7iEdLPRyxYxqUbo5hbTDklJnl0fm26vouRlVmRx6u7IT45ca96uJIIXWfBwkPLJ
    /xgVi5ZqtvMSZYW8Ni55f0dIjpRvvbdfzaYvB/s1QGWTLOV0RY7hw+nRcbaTv/Kv
    R3EG+CdH/G3cOVPx4amme6XBRe/uZnor6QGH+JOSeQKBgQDJxUCJjXyKSFsbf9aW
    MTFikEOSQEcF22kIgyosWcHqNZuc5iYhnsRRiM68VvKwsYmXQFn7ggc06r7Ap8jo
    9SOheZuh3yPnSivdi2gHeTmIvmv3mdPzylIQ8QTFWjIvG4ieIpJlvCcBESfgZn4e
    WGRcIwcIRAS3AebdJrPhXyj8bwKBgQDEOkjG5xa/2tGUtVNoov+0lY+hq8B2XMzb
    +8BQM9BU85/BP/9ngep7Bne2dVBk9iy/1WBsIfKI+hHPI8xP2p+n3C1VdYuqyUqU
    px20CUoxPE9RtE2huxroN7yHLDSy8YxCGQacOJoDPFJtDTL15rGvdQnCagYB7Imq
    K8QPuldNVQKBgA5fGmWxyjkfRj4DMQmpn1bh5643Hdfw9N5CWXKnQgSopNjcG8Mx
    R9J26CLKHqcvPhmj38TmUhUW01dtnAXb0BnkS42QE0KaKd2x3EsL+2keBxqvvkUT
    GB1UzX4xGnn4gBajZ8IPUMfmrOxy4HDQ4vUdGZchISTX4dXGt/FJkeXJAoGAMqYo
    qs5zHMpKVmwHP3bzMZV5IW3Hm8WQSyfMF+eH2qWXkrYGIp1x/JdKxxm4ypaQLmPR
    I5gPljOV7TV8QxBXLWizet+AUXDrgzsve4z6TYMXpis37orxAwd/7hQG9jlKzrTO
    8/vYJQWo8OT7RmVpb7Rx9HCRZGW9kuMBFF4wspECgYBbQmKg/r672pLmtUjKFkLX
    wtSySGJGcQ0fXHBXVuQOQ9GDElPyajMJaRiB0lEmbuO9Esalfcy2DwDVW169xOvP
    X8BASAwspM0jM7+MJirRjATR6xgg0W1c67eQqFulsiOSYcvMsX1tArBN1PCjaTfQ
    t6DEUGdBhcDM8pkKnnnH5A==
    -----END PRIVATE KEY-----

