server:
  port: 8081
  servlet:
    context-path: /medhealth/api

#flyway:
#  repair: true

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/user-service"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.flywaydb: INFO
    org.springdoc: DEBUG

springdoc:
  api-docs:
    path: /document/api-docs
  swagger-ui:
    path: /document/swagger-ui.html

jwt:
  signerKey: "EIG2ryG3InsGo7mStNgivMrw2/OpHD4UrBJUPwkSWacWJaEztRuqsr/axSiuCTxZ"
