server:
  port: 8084
  servlet:
    context-path:

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/report-service"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: true
    out-of-order: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    org.flywaydb: INFO
    org.springdoc: DEBUG

springdoc:
  api-docs:
    path: /document/api-docs
  swagger-ui:
    path: /document/swagger-ui.html

post-service:
  base-url: http://localhost:8083


jwt:
  publicKey: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmqj1di5W7at8KV2C2JKO
    lNg5Pp7DB2I2As/UGwIlUjg7qTUvs43k6VBcDkwHELRISr7yVQsVSo0zugR410fR
    PW3cAiH5V1GF5QMuxzgC6DFYSvivwlaBOqitjK3BU1Ti6GVy0b5WletWq+vJNQN6
    6GXnoWln0ezYWVk+qnbrMcYmetdNrsRmbgDlCK2Dr2yfAXug2DiEU2P915Tjw8AK
    fHv2ASCxtDCQYi9dR94ZejhKVsjifidZL3sv51HxMklhz/weBYviOCmiWy9Gdh+T
    fZVzy0MRoiG3gWAekdVEgeYZW65x5LWHNrShkA3/ZzQIEv98v8GXDwAEAGhLXEIz
    2wIDAQAB
    -----END PUBLIC KEY-----